name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev libncurses-dev zip curl git ccache python3

      - name: Cache Toolchains
        id: cache-toolchains
        uses: actions/cache@v4
        with:
          path: |
            clang
            gcc64
            gcc32
            magiskboot
          key: toolchains-r383902-magiskboot

      - name: Fetch Toolchains
        if: steps.cache-toolchains.outputs.cache-hit != 'true'
        run: |
          mkdir clang && curl -L "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r383902.tar.gz" | tar -xz -C clang
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android11-release gcc64
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android11-release gcc32
          curl -sLo magiskboot https://raw.githubusercontent.com/Uevo001/magiskboot-linux/refs/heads/main/x86_64/magiskboot
          chmod +x magiskboot

      - name: Cache Ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-kernel-${{ github.sha }}
          restore-keys: |
            ccache-kernel-

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/secr5t/android_kernel_CPH2269 -b main kernel_src

      - name: Compile Kernel
        run: |
          export CCACHE_DIR="${HOME}/.ccache"
          export PATH="${GITHUB_WORKSPACE}/clang/bin:${GITHUB_WORKSPACE}/gcc64/bin:${GITHUB_WORKSPACE}/gcc32/bin:$PATH"
          export USE_CCACHE=1
          export CCACHE_EXEC=$(which ccache)
          ccache -M 5G
          cd kernel_src
          make O=out ARCH=arm64 k65v1_64_bsp_defconfig
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC="ccache clang" \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-android- \
            CROSS_COMPILE_ARM32=arm-linux-androideabi-

      - name: Repack Boot Image
        run: |
          chmod +x magiskboot
          curl -sL https://files.catbox.moe/lqh9ks.bin -o boot.img
          ./magiskboot unpack boot.img
          if [ -f kernel_src/out/arch/arm64/boot/Image.gz-dtb ]; then
            cp kernel_src/out/arch/arm64/boot/Image.gz-dtb kernel
          elif [ -f kernel_src/out/arch/arm64/boot/Image.gz ]; then
            cp kernel_src/out/arch/arm64/boot/Image.gz kernel
          else
            cp kernel_src/out/arch/arm64/boot/Image kernel
          fi
          ./magiskboot repack boot.img boot-patched.img

      - name: Upload to Telegram
        run: |
          curl -F chat_id="-1004452787333" \
               -F document=@boot-patched.img \
               -F caption="Kernel build successfully (A.05)" \
               https://api.telegram.org/bot${{ secrets.bot_token }}/sendDocument
