name: Build Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Dependencies
        run: |
          sudo apt update -y && sudo apt upgrade
          sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev libncurses-dev zip curl git ccache python3

      - name: Fetch Toolchains and Tools
        run: |
          mkdir clang && curl -L "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r383902.tar.gz" | tar -xz -C clang
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android11-release gcc64
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android11-release gcc32
          git clone --depth=1 https://android.googlesource.com/platform/system/tools/mkbootimg mkbootimg_tools

      - name: Clone Kernel Source
        run: |
          git clone --depth=1 https://github.com/secr5t/android_kernel_CPH2269 -b main kernel

      - name: Compile Kernel
        run: |
          cd kernel
          export PATH="${GITHUB_WORKSPACE}/clang/bin:${GITHUB_WORKSPACE}/gcc64/bin:${GITHUB_WORKSPACE}/gcc32/bin:$PATH"
          make O=out ARCH=arm64 k65v1_64_bsp_defconfig
          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC=clang \
            CLANG_TRIPLE=aarch64-linux-gnu- \
            CROSS_COMPILE=aarch64-linux-android- \
            CROSS_COMPILE_ARM32=arm-linux-androideabi-

      - name: Repack Boot Image
        run: |
          curl -sL https://files.catbox.moe/lqh9ks.bin -o boot.img
          mkdir boot_out
          python3 mkbootimg_tools/unpack_bootimg.py --boot_img boot.img --out boot_out --format mkbootimg_args > mkbootimg_args.txt
          if [ -f kernel/out/arch/arm64/boot/Image.gz-dtb ]; then
            cp kernel/out/arch/arm64/boot/Image.gz-dtb boot_out/kernel
          elif [ -f kernel/out/arch/arm64/boot/Image.gz ]; then
            cp kernel/out/arch/arm64/boot/Image.gz boot_out/kernel
          else
            cp kernel/out/arch/arm64/boot/Image boot_out/kernel
          fi
          python3 mkbootimg_tools/mkbootimg.py $(cat mkbootimg_args.txt) -o boot-patched.img

      - name: Upload to Telegram
        run: |
          curl -F chat_id="-1004452787333" \
               -F document=@boot-patched.img \
               -F caption="Kernel build successfully (A.05)" \
               https://api.telegram.org/bot${{ secrets.bot_token }}/sendDocument
               