name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Kernel Source
        run: |
          git clone https://github.com/secr5t/android_kernel_CPH2269 --depth 1 android_kernel

      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: android_kernel/
          config: k65v1_64_bsp_defconfig
          arch: arm64
          aosp-gcc: true
          ccache: true
          aosp-clang: true
          android-version: 11
          aosp-clang-version: r383902
          anykernel3: true
          release: true
          access-token: ${{ secrets.GITHUB_TOKEN }}
